/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 10-апр-2018 1:16:20 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `file_lister`
;

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `extension` CASCADE
;

DROP TABLE IF EXISTS `file` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

DROP TABLE IF EXISTS `users_extensions` CASCADE
;

DROP TABLE IF EXISTS `config` CASCADE
;

DROP TABLE IF EXISTS `message` CASCADE
;

/* Create Tables */

CREATE TABLE `extension`
(
	`ext_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`ext_name` VARCHAR(256) NOT NULL,
	CONSTRAINT `PK_extension` PRIMARY KEY (`ext_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `file`
(
	`f_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`f_name` VARCHAR(1000) NOT NULL,
	`f_hash` CHAR(40) 	 NULL,
	`f_size` INT 	 UNSIGNED NULL,
	`f_date` BIGINT 	 UNSIGNED NULL,
	`u_id` BIGINT 	 UNSIGNED NULL,
	`ext_id` BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `PK_file` PRIMARY KEY (`f_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `user`
(
	`u_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`u_name` VARCHAR(255) NOT NULL,
	`u_login` VARCHAR(255) NOT NULL,
	`u_password` VARCHAR(255) NOT NULL,
	`u_email` VARCHAR(255) NOT NULL,
	`u_spacelimit` INT NOT NULL,
	`u_foldername` VARCHAR(2000) 	 NULL,
	`u_auth_token` TINYTEXT 	 NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`u_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `users_extensions`
(
	`u_id` BIGINT UNSIGNED NOT NULL,
	`ext_id` BIGINT UNSIGNED NOT NULL,
	`u_ext_maxsize` INT 	 UNSIGNED NULL,
	CONSTRAINT `PK_users_extensions` PRIMARY KEY (`u_id` ASC, `ext_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `config`
(
	`setting_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`setting_key` TINYTEXT 	 NULL,
	`setting_val` VARCHAR(255) 	 NULL,
	CONSTRAINT `PK_config` PRIMARY KEY (`setting_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT='This config could contain other things like references to app languages (should be stored in a separate table) and other site-wide settings.'

;

CREATE TABLE `message`
(
	`msg_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`msg_code` VARCHAR(255) 	 NULL,
	`msg_text_en` TEXT 	 NULL,
	CONSTRAINT `PK_message` PRIMARY KEY (`msg_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `extension` 
 ADD CONSTRAINT `UNQ_extension` UNIQUE (`ext_id` ASC)
;

DELIMITER //
DROP TRIGGER IF EXISTS trigger_notempty_check//
CREATE TRIGGER trigger_notempty_check BEFORE INSERT ON extension
    FOR EACH ROW 
  BEGIN 
  SET @x = (SELECT Count(ext_name) FROM extension WHERE ext_name = '');
        IF (NEW.ext_name = '') AND (@x > 0) THEN 
        SIGNAL SQLSTATE '45000' SET message_text ='Only one empty extension name allowed';
        END IF; 
  END 
//
DELIMITER ;
;

ALTER TABLE `file` 
 ADD CONSTRAINT `UNQ_file_id` UNIQUE (`f_id` ASC)
;

ALTER TABLE `file` 
 ADD INDEX `IXFK_file_user` (`u_id` ASC)
;

ALTER TABLE `user` 
 ADD CONSTRAINT `UNQ_u_id` UNIQUE (`u_id` ASC)
;

DELIMITER //
DROP TRIGGER IF EXISTS `uniquefoldername`//
CREATE TRIGGER `uniquefoldername` BEFORE INSERT ON `user`
FOR EACH ROW
  BEGIN
    SET @x = (SELECT AUTO_INCREMENT
FROM information_schema.tables
WHERE table_name = 'user'
AND table_schema = DATABASE( ) );
    SET  NEW.u_foldername = concat(NEW.u_name, @x);
  END // 
//
DELIMITER ;
;

ALTER TABLE `users_extensions` 
 ADD CONSTRAINT `UNQ_user_ext_spacelimit` UNIQUE (`u_id` ASC, `ext_id` ASC) 
COMMENT 'The first two columns (user_id AND extension_id) must not be repeated. However one user or one extension can repeat several times for different extensions or users, respectively.' 
;

/* Create Foreign Key Constraints */

ALTER TABLE `file` 
 ADD CONSTRAINT `FK_file_extension`
	FOREIGN KEY (`ext_id`) REFERENCES `extension` (`ext_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `file` 
 ADD CONSTRAINT `FK_file_user`
	FOREIGN KEY (`u_id`) REFERENCES `user` (`u_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `users_extensions` 
 ADD CONSTRAINT `FK_users_ext_user`
	FOREIGN KEY (`u_id`) REFERENCES `user` (`u_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `users_extensions` 
 ADD CONSTRAINT `FK_users_extensions_extension`
	FOREIGN KEY (`ext_id`) REFERENCES `extension` (`ext_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
